server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 666666
    url: jdbc:mysql:///internship_platform
  #    password: Kf20011201
#    url: jdbc:mysql://101.200.123.125:3306/internship_platform
  redis:
    port: 6379
    host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.fan: debug

mybatis-plus:
  type-aliases-package: com.fan.*.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml